version: '3.1'

services:
  db:
    image: postgres:13.1-alpine
    privileged: true
    expose:
      - 5432
    environment:
      POSTGRESS_USER: person
      POSTGRESS_PASSWORD: 123456
      POSTGRESS_DB: todo
#      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    build:
      context: .
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py create_data
      && gunicorn DRF_Project.wsgi 0.0.0.0:8080
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend