# Generated by Django 4.0 on 2022-01-14 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('145ef2cc-22a2-420a-97cb-06ed73095220'), primary_key=True, serialize=False),
        ),
    ]
